buildVariable: false
familyName: Noto Sans Math
googleFonts: true
includeSubsets:
- from: Noto Sans
  ranges:
      - from: 0x00A2
        to: 0x00A3
      - from: 0x00A5
        to: 0x00A5
      - from: 0x00A9
        to: 0x00A9
      - from: 0x00AE
        to: 0x00AE
      - from: 0x00B0
        to: 0x00B0
      - from: 0x00B7
        to: 0x00B7
      - from: 0x00C5
        to: 0x00C5
      - from: 0x00C7
        to: 0x00C7
      - from: 0x00D0
        to: 0x00D0
      - from: 0x00DE
        to: 0x00DE
      - from: 0x00E5
        to: 0x00E5
      - from: 0x00E7
        to: 0x00E7
      - from: 0x00F0
        to: 0x00F0
      - from: 0x00FE
        to: 0x00FE
      - from: 0x02C6
        to: 0x02C6
      - from: 0x0410
        to: 0x044F
      - from: 0x2021
        to: 0x2021
      - from: 0x20AC
        to: 0x20AC
      - from: 0x2118
        to: 0x2118
      - from: 0x2127
        to: 0x2127
sources:
  - NotoSansMath.glyphspackage
